config/routes.rb
Upstart::Application.routes.draw do
  root :to => "pages#home"
  get 'about' => 'pages#about'
  get 'event' => 'pages#event'
  get 'contact' => 'pages#contact'
  get 'resource' => 'pages#resource'
  get 'jobs' => 'pages#jobs'
  get 'school' => 'pages#school'
  get 'discovery' => 'pages#discovery'
  get 'forum' => 'pages#forum'

  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def event
  end

  def contact
  end

  def resources
  end

  def school
  end

  def discovery
  end

  def forum
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def title(page_title)
  		content_for(:title) { page_title }
	end


end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
  </div>
</div>
<footer>
    <div class="footer">
      <div class="container">
          <div class="row">

            <div class="span2">
              <h5>UpStart</h5>
              <ul>
                <li><%= link_to("About", about_path) %></li>
                <li><a href="#">Press</a></li>
                <li><%= link_to("Contact", contact_path) %></li>
              </ul>
            </div>

            <div class="span2">
              <h5>Community</h5>
              <ul>
                <li><a href="#">Blog</a></li>
                <li><a href="http://www.facebook.com/upstartinnovationsociety">Facebook</a></li>
                <li><a href="http://www.twitter.com/upstartutsc">Twitter</a></li>
              </ul>
            </div>
          </div>
            

            <div id="credit">
              <small>Crafted with &hearts; in Toronto by <%= link_to("@kwngo", "http://twitter.com/kwngo") %></small>
            </div>
            
        </div>
      </div> <!-- /bottom-menu-inverse -->
    </div>
  </footer>
</body>
</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Upstart | <%= content_for?(:title) ? content_for(:title) : 'We Do Workshops' %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <!-- Loading stylesheets and javascript -->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    
    <link rel="shortcut icon" href="images/favicon.ico">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
    <![endif]-->

  </head>
  <body>
  <%= render 'layouts/navigation' %>

app/views/layouts/_navigation.html.erb
<div id="wrap">
  <div id="main">
      <div class="navbar">
            <div class="navbar-inner navbar-static-top">
              <div class="container">
                <%= link_to "UpStart", root_path, :class => "brand" %>

                <div class="row">

                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target="#nav-collapse-01">
                </button>
                    <div class="nav-collapse collapse" id="nav-collapse-01">
                    <ul class="nav">
                      <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">About<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                          <li><%= link_to "Overview", about_path %></a></li>
                          <li><%= link_to "Events & Schedule", event_path %></a></li>
                          <li><%= link_to "Jobs", jobs_path %></a></li>
                          <li><%= link_to "Contact Us", contact_path %></a></li>
                        </ul>
                      </li>
                      <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">Programs<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                          <li><%= link_to("StartupSchool", school_path) %></li>
                          <li><%= link_to "SmashUp", "http://smashup.upstartutsc.com/   " %></li>
                          <li class="divider"></li>
                          <li><%= link_to("Discovery Network", discovery_path) %></li>
                        </ul>
                      <li><%= link_to "Resources", resource_path %></li>
                    </ul>
                   <!-- /nav -->
                </div><!--/.nav-collapse -->
                </div>
              </div>
            </div>
          </div> <!-- /navbar -->

app/views/layouts/application.html.erb
<%= render 'layouts/header' %>

<body>

<%= yield %>

	<%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/about.html.erb
<% title "About Us" %>

<div id="aboutbox" class="contentbox">
	<div class="row">
		<div class="secondarybox">
			<h4>"I think a simple rule of business is, if you do the things that are easier first, then you can actually make a lot of progress."</h4>
			<small>- Mark Zuckerberg, Founder & CEO of Facebook</small>
		</div>
	</div>
</div>

<section>
	<div class="single">
		<div class="content">


			<h2><%= yield(:title) %></h2>
			
			
			
			<p>At UpStart we have only one mission: <b>to create a generation of students that have the courage, and ability, to disrupt the world.</b> We realize that there's a huge gap between the knowledge we're taught in business school and the skills we'll need to survive out in the real world.</p>

			<p>For years, we've been told that if we study hard, pay our dues and slowly work our way up the corporate ladder that we would find success and happiness. Instead, many of us found that instead of happiness it has proved to be a cruel game designed to sap creativity and joy out of our lives. But the world is changing. Today, the world thrives on innovation, technology and design. <em>In this world, it isn't enough to just fit in. To succeed, we'll have to have both the courage and ability to be oustanding.</em></p>
			<br />


			<h4>So what do we do?</h4>

			 <p>How are we trying to bridge this gap? Through StartupSchool, we help students develop their critical thinking and technical skills: how to go from ideation to execution. At SmashUp, our annual entrepreneurship conference, students get the opportunity to work with students from across Canada and actually apply their learning to creating a real product/business. Lastly we're developing an online platform for students to connect, share ideas and work on projects.</p>

			<p>If any of this resonates with you at all, please come visit us! We are based in the Ideation + Experiential Learning Centre (The Hub) in UTSC and host a variety of workshops on and off campus. </p>

		</div>

		<div class="content">
			
		
			<h3>Meet the team that makes it all happen</h3>
			<a data-overlayer="effect:bottom;" href="http://www.twitter.com/kwngo">
			    <%= image_tag('kareem.jpg') %>
			    <div class="overlay">Kareem Kwong, President</div>
			</a>
			<a data-overlayer="effect:bottom;" href="#">
			    <%= image_tag('eunice.jpg', :class => "profile") %>
			    <div class="overlay">Eunice Lee, Vice-President of Operations</div>
			</a>
			
			<a data-overlayer="effect:bottom;" href="#">
			    <%= image_tag('vania.jpg', :class => "profile") %>
			    <div class="overlay">Vania Putri, Vice-President of Marketing</div>
			</a>
			<a data-overlayer="effect:bottom;" href="#">
			    <%= image_tag('winson.jpg') %>
			    <div class="overlay">Winson Leung, Marketing Manager</div>
			</a>
			<a data-overlayer="effect:bottom;" href="#">
			    <%= image_tag('laxitha.jpg', :class => "profile") %>
			    <div class="overlay">Laxitha Kathir, Marketing Manager</div>
			</a>
			<a data-overlayer="effect:bottom;" href="#">
			    <%= image_tag('ishita.jpg', :class => "profile") %>
			    <div class="overlay">Ishita Agrawal, Business Development Manager</div>
			</a>
			<a data-overlayer="effect:bottom;" href="#">
			    <%= image_tag('renee.jpg', :class => "profile") %>
			    <div class="overlay">Renee Wong, Marketing Manager</div>
			</a>
			<a data-overlayer="effect:bottom;" href="#">
			    <%= image_tag('jasmine.jpg', :class => "profile") %>
			    <div class="overlay">Jasmine Marcial, Operations Manager</div>
			</a>
			<a data-overlayer="effect:bottom;" href="#">
			    <%= image_tag('john.jpg', :class => "profile") %>
			    <div class="overlay">Johnathan Chau, Operations Manager</div>
			</a>
			<a data-overlayer="effect:bottom;" href="#">
			    <%= image_tag('brintha.jpg', :class => "profile") %>
			    <div class="overlay">Brintha K, Marketing Manager</div>
			</a>
			<a data-overlayer="effect:bottom;" href="#">
			    <%= image_tag('sravanti.jpg', :class => "profile") %>
			    <div class="overlay">Sravanti Mudunuri, Business Development Manager</div>
			</a>
			<br />
			<br />
			<p>We're always looking for amazing people to be part of our team! <%= link_to("Apply Today", jobs_path, class: "btn-secondary") %></p>

		</div>
	</div>
</section>
		        	

app/views/pages/contact.html.erb
<% title "Contact Us" %>

<div id="contactbox" class="contentbox">
	<div class="row">
		<div class="secondarybox">
			<h4>"What I tell everyone, and I really do for myself is, I have a long-run dream, which is I want to work on stuff that I think matters."</h4>
			<small>Sheryl Sandberg - Author of Lean In & COO of Facebook</small>
		</div>
	</div>
</div>

<section>
	<div class="single">
		<div class="content">
			<h2><%= yield(:title) %></h2>
			<p>If you want to talk about potential partnerships or have any other questions, please contact <a href="emailto:kareem.kwong@gmail.com">kareem.kwong@gmail.com</a></p>

			<h3>Our Address</h3>
			<strong>University of Toronto Scarborough</strong>
			<p>1265 Military Trail<br/>
				Toronto, ON<br/>M1C 1A4</p>
		</div>
	</div>
</section>

app/views/pages/discovery.html.erb
<div class="single">
	<div class="content">
	Currently building...
	</div>
</div>

app/views/pages/event.html.erb
<% title "Events" %>


<div id="eventbox" class="contentbox">
	<div class="row">
		<div class="secondarybox">
			<h4>“Everyone has an idea. But it’s really about executing the idea and attracting other people to help you work on the idea.”</h4>
			<small>- Jack Dorsey, Co-Founder of Twitter and Co-Founder & CEO of Square</small>
		</div>
	</div>
</div>


<section>
	<div class="single">
		<div class="content">
			<h2><%= yield(:title) %></h2>

			<p>Currently building...</p>
		</div>
	</div>
</section>
		        	

app/views/pages/home.html.erb
<div class="gallery autoplay items-3">
    <div id="item-1" class="control-operator"></div>
    <div id="item-2" class="control-operator"></div>
    <div id="item-3" class="control-operator"></div>
    <div id="item-4" class="control-operator"></div>



    <figure class="item first">

      <div class="container">
        <div class="row">
    
      <header class="text-block">   

      <h1>We Like To Think We're In The Business of Disruption</h1>
      <p>UpStart is creating entrepreneurial experiences to prepare our students for the harsh, desolate wasteland that is the real world. We're just trying to re-imagine business education across the country. Based in the University of Toronto Scarborough.</p>
       <%= link_to("Learn More", about_path, :class => "btn-secondary") %>
       </header>
       </div>
      </div>   
    </figure>

    <figure class="item second">
      <header class="text-block">   

      <h1>We Host Awesome Workshops</h1>
      <p>We're working with local partners to bring incredible skill-based workshops to UTSC.</p>
      <%= link_to("See Upcoming Workshops", event_path, :class => "btn-secondary") %>
      </header>

    </figure>

    <figure class="item third">
      <header class="text-block">   

      <h1>A Great Team Is Everything</h1>
      <p>None of this would be possible without our fantastic team who work hard to make the school a better place for learning. Join us today!</p>
      <%= link_to("Join The Team", jobs_path, :class => "btn-secondary") %>
      </header>
    </figure>

    <figure class="item fourth">
      <header class="text-block">   
      <h1>We Eat, Sleep and Dream About Social</h1>
      <p>We use social media to reach you where you're most comfortable (ie. At home in your pyjamas) Follow us on Facebook and Twitter for the latest startup news and resources!</p>
      <%= link_to("Follow us on Faceboook", "facebook.com/upstartinnovationsociety", :class => "btn-secondary") %>
      </header>
    </figure>

    <div class="controls">
      <a href="#item-1" class="control-button">•</a>
      <a href="#item-2" class="control-button">•</a>
      <a href="#item-3" class="control-button">•</a>
      <a href="#item-4" class="control-button">•</a>ggaaa
    </div>
  </div>

  

  <div id="about-row">
    <div id="block" class="container">
        <div class="row">
          <div class="span4">
          <%= image_tag("Bulb.png", :class => "main-icons") %>
           <h4>StartupSchool</h4>
           <h5>We host a collection of experiential, hands-on workshops to help students build businesses and take their ideas from ideation to execution.</h5>
         </div>
         <div class="span4">
          <%= image_tag("Spaceship.png", :class => "main-icons") %>
           <h4>SmashUp</h4>
           <h5>Every year, students from across Canada come together for 2 days of intense skill-based entrepreneurial workshops and launching their own startups.</h5>
         </div>
         <div class="span4">
          <%= image_tag("Girl.png", :class => "main-icons") %>
           <h4>Discovery Network</h4>
           <h5>We help UTSC students connect with talent and potential co-founders</h5>
         </div>
        </div>
     
    </div>
  </div>

   <div id="email-row">
    <div class="container">
      <div class="row">
        <div class="center">
          <div class="span12">

          <!-- Begin MailChimp Signup Form -->
            
            <form action="http://upstartutsc.us7.list-manage1.com/subscribe/post?u=b83e518f4825ca0a285e38d08&amp;id=69e198b1cd" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
              <h4>Sign Up For Our Newsletter And Be The First <br/>To Know About Our Workshops and Events!</h4>
              <label for="mce-EMAIL">Email Address</label>
              <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
              <div id="mce-responses" class="clear">
                <div class="response" id="mce-error-response" style="display:none"></div>
                <div class="response" id="mce-success-response" style="display:none"></div>
              </div>  <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="btn btn-primary btn-wide"></div>
            </form>
            </div>
<!--End mc_embed_signup-->
          </div>
        </div>
      </div>
    </div>
  </div>

  

app/views/pages/jobs.html.erb
<% title "Jobs" %>


<div id="contactbox" class="contentbox">
	<div class="row">
		<div class="secondarybox">
			<h4>"“The only way to do great work is to love what you do. If you haven’t found it yet, keep looking. Don’t settle. As with all matters of the heart, you’ll know when you’ve found it.”</h4>
			<small>- Steve Jobs (1955-2011) Co-founder, CEO and Chairman of Apple</small>
		</div>
	</div>
</div>


<section>
	<div class="single">
		<div class="content">
		<h2><%= yield(:title) %></h2>

<h4>We are hiring!</h4>
<p>We can’t wait to see your applications! Please submit an <a href="https://docs.google.com/forms/d/1G9-Vpo5PpTPUjCIeZsmeqDOnTXlkA49O72JXQ0Ed5dc/viewform">Application form</a> and send your resume to Jon Zhou, Operations Manager <a href="emailto:jasmine@upstartutsc.com">jonathan@upstartutsc.com</a> with the subject line “UpStart 2013-2014 Applicant Name”. Applications are due Monday September 30th, 11:59PM EST</p>
<br/> 	
Join UpStart and you’ll have an opportunity to:
<ul>
	<li>* Help students build their businesses and develop their ideas</li>
	<li>* Plan and execute on SmashUp, a two day start-up competition that will bring together students from across the country to build businesses and products</li>
	<li>* Work with industry professionals, entrepreneurs and start-ups to bring workshops and events to UTSC
</li>

	<li>* Excel in a fun, fast-paced and extremely collaborative team environment</li>
</ul>
<br />

<h3>Marketing Team</h3>

<p><strong>Graphic Designers (2)</strong></p>

<p>We are looking for driven and passionate Graphic Designers that have a raw talent for colours, typography and illustration. As a graphic designer you will work within the marketing team to creating beautiful, creative and effective marketing materials. You will be responsible for representing UpStart’s brand, as well as expected to take it in exciting new directions. UpStart is a great place for a graphic designer to thrive and build their portfolio because we value collaboration and ideas over process and structure.</p>

<em>Skills</em>
<ul>
	<li>* Experienced with Adobe Photoshop, Illustrator and InDesign in designing for print and web (posters, sponsorship packages, banners, and logos).</li>
	<li>* Thrives in a fun, fast-paced team environment</li>
	<li>* Passionate about branding, illustration and design</li>
	<li>* Ability to code in HTML/CSS/JS is not required but is definitely an asset.</li>
	<li>* A sample of past work will be required.</li>
</ul>

<br />
<br />

<h3>Business Development Team</h3>

<p><strong>Business Development Managers (2)</strong></p>

<p>We are looking for an elite-level business development manager with experience. A true hunter, you are assertive, tenacious, and passionate about reaching out to potential partners. You want to build amazing relationships that help grow UpStart, The Hub and UTSC. You're obsess 24/7 over bringing in the partners we need to deliver great workshops. UpStart is a great place to push your boundaries and develop your skills because we value collaboration and ideas over process and structure.</p>

<em>Skills</em>
<ul>
	<li>* "Must do" attitude; Assertive, passionate, and fearless</li>
	<li>* Strong verbal communication and interpersonal skills</li>
	<li>* Knowledgeable about entrepreneurship and start-ups in general</li>
</ul>
<br/>
<br/>

<h3>Operations Team</h3>

<strong>Operations Manager (1)</strong>

<p>We are keeping our eye out for an assertive and go-getter Operations Manager who will be responsible for the strategy and implementation of our skills-based workshops at UTSC as well as the SmashUp Conference in 2014. You will be responsible for managing event logistics and ensuring that event run smoothly. As an Operations Manager, you will also handle all Human Resource initiatives and manage the financial aspects of the organization. The best Operations Manager has a student-centered mindset, and stop at nothing to deliver exceptional event experiences.</p>

<em>Skills</em>
<ul>
	<li>* Experience with event coordination and planning</li>
	<li>* Excellent analytical, communication and interpersonal skills</li>
	<li>* Proficient in Microsoft Office (Excel, Word, PowerPoint)</li>
	<li>* Knowledgeable about entrepreneurship and start-ups in general</li>
</ul>

<br />

<strong>IT Manager(1)</strong>

<p>We need a talented Information Technology Manager who can turn communicate beautiful ideas into functioning and beautiful concepts. As the IT Manager, you will be working within the Operations team to build websites and applications for our workshops and conferences. UpStart is a great place to thrive and build their portfolio because we value collaboration and ideas over process and structure.</p>

<em>Skills</em>

<ul>
	<li>* Ability to code in HTML/CSS/JS is required</li>
	<li>* Experience with or willing to learn how to use Ruby on Rails, Github & Heroku</li>
	<li>* Past experience with MVC frameworks is a bonus</li>
	<li>* A sample of past work will be required</li>
</ul>
		</div>
	</div>

	<div class="single">
		<div class="content">
				<h3>Our Programs</h3>
		         <p>Check out some of the projects you will be working on!</p>
			<div class="row">
		          <div class="span4">
		     
		          <%= image_tag("Bulb.png", :class => "main-icons") %>
		           <h4>StartupSchool</h4>
		           <h5>We host a collection of experiential, hands-on workshops to help students build businesses and take their ideas from ideation to execution.</h5>
		         </div>
		         <div class="span4">
		          <%= image_tag("Spaceship.png", :class => "main-icons") %>
		           <h4>SmashUp</h4>
		           <h5>Every year, students from across Canada come together for 2 days of intense skill-based entrepreneurial workshops and launching their own startups.</h5>
		         </div>
		         <div class="span4">
		          <%= image_tag("Girl.png", :class => "main-icons") %>
		           <h4>Discovery Network</h4>
		           <h5>We help UTSC students connect with talent and potential co-founders.</h5>
		         </div>
		        </div>
			</div>
	</div>
</section>

app/views/pages/resource.html.erb
<% title "Resources" %>

<div id="resourcebox" class="contentbox">
	<div class="row">
		<div class="secondarybox">
			<h4>“If you want to create a great product, just focus on one person. Make that one person have the most amazing experience ever."
			</h4>
			<small>- Brian Chesky, Co-Founder & CEO of Airbnb</small>
		</div>
	</div>
</div>

<section>
	<div class="single">
		<div class="content">
			<h2><%= yield(:title) %></h2>
			<em>Currently under construction!</em>

			<p>This is where you will find the best videos, articles and tools for students trying to work on their ideas and business</p>
					<h4>Strategy Tools</h4>
					<ul>
						<li><a href="http://www.businessmodelgeneration.com/canvas">Business Model Canvas</a></li>
					</ul>
				
					<h3>Lean Methodology Sources</h3>
					<ul>
						<li><a href="http://steveblank.com/">Steve Blank</a></li>
						<li><a href="http://www.startuplessonslearned.com/">Eric Ries</a></li>
					</ul>

					<em>Also check out some of UpStart's great events happening <%= link_to('here', event_path) %><em>
		</div>
		
	</div>
</section>

app/views/pages/school.html.erb
<% title "Startup School" %>


<div class="single">
	<div class="content">

	<h2><%= yield(:title) %></h2>

	<p>
		UpStart hosts workshops throughout the year to arm students with the weaponry they need to wreck havoc on the business world. We work with our fantastic local partners to teach modern topics and skills that you won't learn in school.
	</p>
	<p>
		To bombard you with some of our workshop topics: 
		<ul>
			<li>Business Design</li>
			<li>Growth Hacking</li>
			<li>Building Websites with Ruby on Rails</li>
			<li>Startup Marketing</li>
			<li>Customer Development</li>
			<li>How to Pitch to a VC</li>
			<li>Building Brands</li>
			<li>Product Development</li>
		</ul>
		
		Wooo, overwhelmed yet?
	</p>

	</div>
</div>